spring:
  application:
    name: payment
  datasource:
    url: jdbc:postgresql://localhost:5432/mq_messages
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
ibm:
  mq:
    host: localhost
    port: 1414
    queue-manager: QM1
    channel: DEV.APP.SVRCONN
    queue: DEV.QUEUE.1
    user: app
    password: app_password
