services:
  ibm-mq:
    image: icr.io/ibm-messaging/mq
    container_name: ibm-mq
    ports:
      - "1414:1414" # MQ listener port
      - "9443:9443" # Web console
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQ_ADMIN_PASSWORD=passw0rd
      - MQ_APP_PASSWORD=app_password
      - MQ_DEV=true # Set to true for development with relaxed security
    volumes:
      - qm1data:/mnt/mqm
    networks:
      - mq-postgres-net

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: mq_messages
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mq-postgres-net

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - mq-postgres-net

volumes:
  qm1data:
  postgres-data:

networks:
  mq-postgres-net:
    driver: bridge